//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolfLairBlog.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLog_Error
    {
        public int ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Origin { get; set; }
        public string LogLevel { get; set; }
        public string Message { get; set; }
        public string Exception { get; set; }
        public string StackTrace { get; set; }
    }
}
